name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Codesign executable
        env: 
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}

        run: |
          base64 --decode $MACOS_CERTIFICATE > certificate.p12
          security create-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_NAME
          security default-keychain -s $KEYCHAIN_NAME
          security unlock-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_NAME
          security import certificate.p12 -k $KEYCHAIN_NAME -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $KEYCHAIN_PASSWORD $KEYCHAIN_NAME

      - name: Build and test
        run: xcodebuild clean test -scheme 'Mergician' | xcpretty
